version: '3.7'

services:
  db-postgres:
    image: postgres:11.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netomerch
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend
    hostname: db-postgres

  api:
    image: mikeproalfamailru/netomerch-backend:latest
    environment:
      SECRET_KEY: django-insecure-nw^y+m^wmxza1asgk+)!ua2qx9)g+#v=6%76-9i8i(6eqiw94j
      DEBUG: 1
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_NAME: netomerch
      DB_HOST: db-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    command: sh /netomerch-backend/run.sh
    depends_on:
      - db-postgres
    ports:
      - 8000:8000
    networks:
      - backend
    hostname: api

networks:
  backend:
    name: backend

volumes:
  pg-data:
