name: ci

on: push

env:
  DC_FILE: ""
  DC_ENV: ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Upload docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.LOGIN }}
          key: ${{ secrets.SSH_KEY }}
          source: "deploy/*"
          target: "~/srv/netomerch/backend/${{ env.MODE }}"
#          strip_components: 1



#      - name: Upload docker-compose
#        uses: appleboy/scp-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.LOGIN }}
#          key: ${{ secrets.SSH_KEY }}
#          source: "deploy-dev/*"
#          target: "~/netomerch/backend/${{ env.MODE }}"
#          strip_components: 1
#
#      - name: Connect via SSH, pull, restart
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.LOGIN }}
#          key: ${{ secrets.SSH_KEY }}
#          script: |
#            export SECRET_KEY=$(echo $RANDOM | md5sum | head -c 20; echo;)
#            export REPO_NAME=${{ github.repository }}
#            mkdir -p ~/netomerch/backend/test
#            cd ~/netomerch/backend/test
