name: ci

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:dev

      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-host: ${{ secrets.SERVER_IP }}

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Pull and restart
        run: |
          cd ${{ github.workspace }}/deploy-dev
          echo install docker-compose $(date)
          sudo pip install docker-compose
          echo Instaled $(date)
          export SECRET_KEY=$(echo $RANDOM | md5sum | head -c 20; echo;)
          echo $SECRET_KEY $(date)
          export REPO_NAME=${{ github.repository }}
          echo $REPO_NAME
          echo create remote context $(date)
          docker context create remote --docker "host=ssh://${{ secrets.LOGIN }}@${{ secrets.SERVER_IP}}"
          echo use remote context $(date)
          docker context use remote
          echo pull $(date)
          docker pull ghcr.io/${{ github.repository }}:dev
          echo down $(date)
          docker-compose --context remote down
          echo up $(date)
          docker-compose --context remote up -d
          echo rm old images $(date)
          for image in $(docker image ls| grep none|awk '{print $3}' | cat) ; do docker image rm "$image"; done
          echo all done $(date)
