name: ci

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:dev

      - name: Tar
        run: |
          cd ${{ github.workspace }}/deploy-dev
          tar -cf deploy-dev.tar *


      - name: upload docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.LOGIN }}
          key: ${{ secrets.SSH_KEY }}
          source: "${{ github.workspace }}/deploy-dev/deploy-dev.tar"
          target: "/srv/netomerch/backend/"

      - name: Connect via SSH, pull, restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.LOGIN }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /srv/netomerch/backend/
            mkdir -p -m 770 deploy-dev
            tar -xfv /srv/netomerch/backend/github/workspace/deploy-dev/deploy-dev.tar -C ./deploy-dev/
            cd deploy-dev && chmod 660 *
            export SECRET_KEY=$(echo $RANDOM | md5sum | head -c 20; echo;)
            echo $SECRET_KEY $(date)
            export REPO_NAME=${{ github.repository }}
            echo $REPO_NAME $(date)
            echo pull $(date)
            docker pull ghcr.io/${{ github.repository }}:dev
            echo down $(date)
            docker-compose down
            echo up $(date)
            docker-compose up -d
            rm /srv/netomerch/backend/github/workspace/deploy-dev/deploy-dev.tar
