name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: ghcr.io/${{ github.repository }}:latest

      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-host: ${{ secrets.SERVER_IP }}

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Deploy
        run: |
          echo ${{ github.workspace }}
          ls -la ${{ github.workspace }}/..

#          cd ${{ github.workspace }}/deploy-dev

#          sudo pip install docker-compose
#          cd ${{ github.event.workspace }}/deploy-dev
#          export SECRET_KEY=${{ secrets.SECRET_KEY }}
#          docker context create remote --docker "host=ssh://${{ secrets.LOGIN }}@${{ secrets.SERVER_IP}}"
#          docker context use remote
#          docker pull ghcr.io/mikepro-alfamail-ru/cicd_testing:latest
#          docker-compose --context remote down
#          docker-compose --context remote up -d --force-recreate






