name: ci

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:dev

      - name: Setup SSH
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-host: ${{ secrets.SERVER_IP }}

      - name: Setup python
        uses: actions/setup-python@v2

      - name: Pull and restart
        run: |
          cd ${{ github.workspace }}/deploy-dev
          sudo pip install docker-compose
          echo Instaled
          export SECRET_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
          echo $SECRET_KEY
          export REPO_NAME=${{ github.repository }}
          echo $REPO_NAME
          docker context create remote --docker "host=ssh://${{ secrets.LOGIN }}@${{ secrets.SERVER_IP}}"
          docker context use remote
          docker pull ghcr.io/${{ github.repository }}:dev
          docker-compose --context remote down
          docker-compose --context remote up -d
          for image in $(docker image ls| grep none|awk '{print $3}' | cat) ; do docker image rm "$image"; done
