name: secrets

on: push

jobs:
  secr:
    runs-on: ubuntu-latest
    steps:
      - name: print secrets
        env:
          GITHUB_CONTEXT: ${{ toJSON(secrets) }}
        run: echo "$GITHUB_CONTEXT"

      - name: print
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
